version: "3.8"

services:
  app:
    container_name: tickes-reactpagos
    image: tickes-reactpagos
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5055:3000"
